### ISSUE TITLE
Incorrect documentation

### ISSUE THREAD

**Issue by pozsa** [eth-cscs/firecrest#124]
https://firecrest-api.cscs.ch/#/Compute/get_compute_jobs__jobid_ is not documented correctly.
The endpoint does not return a `Job`, but rather a `Task`.

**Comment by jpdorsch** [comment]
Hi @pozsa, thanks for the comment. 

This issue is related to the web API specification at CSCS (https://firecrest-api.cscs.ch), not to this repository.

Now, answering your issue, the endpoint `GET /compute/job/<jobid>` does respond a reference to a `Task` object, because, in order to check the availability of a `Job` in the queue, it needs to create an asynchronous `Task`. 
This is due to a possible block time that can exist in the meantime between the request is done and the SLURM backend responses. We have experimented with this situation in our tests machines with thousand of jobs running.

The explanation is more detailed here https://firecrest.readthedocs.io/en/latest/overview.html#compute-microservice.

I think that this also solves the issue #125 

Cheers.

**Comment by pozsa** [comment]
What platform would be the right place to request fixing the documentation at https://firecrest-api.cscs.ch/ ?

**Comment by jpdorsch** [comment]
That would be the support portal at CSCS: https://support.cscs.ch/
