### ISSUE TITLE
How can I find the login token?

### ISSUE THREAD

**Issue by simonbray** [eth-cscs/firecrest#166]
Hi there, I've launched the demo and would like to start making a few API calls through pyFirecREST. How can I find the required access token? I wasn't able to find the information on GitHub or the readthedocs site.

Thank you for your help,

Simon

**Comment by ekouts** [comment]
Hi, in order to get an access token you need to make first a request to the keycloak container of the demo environment. That would be something like this:
```bash
curl -s -X POST http://localhost:8080/auth/realms/kcrealm/protocol/openid-connect/token \
     --data "grant_type=client_credentials" \
     --data "client_id=firecrest-sample" \
     --data "client_secret=b391e177-fa50-4987-beaf-e6d33ca93571"
```

This will return with a short-lived token and you can make requests to `http://localhost:8000` as long as the token is valid. If you don't want to have to deal with the token expiration you can also have a look at pyfirecrest, a python wrapper for the firecrest api: https://github.com/eth-cscs/pyfirecrest .

**Comment by simonbray** [comment]
Great, thank you for the super fast response! Actually, I am using pyfirecrest already. How does that help get around the token expiration issue?

**Comment by ekouts** [comment]
My answer was a bit misleading maybe, I only meant you won't have to make requests for new token explicitly. Whenever you are trying to make a request through pyfirecrest (if you are using the [ClientCredentialsAuth](https://github.com/eth-cscs/pyfirecrest/blob/main/firecrest/Authorization.py#L11) object), firecrest will check how much time you token has left and if it is less than 10 seconds(this is configurable), it will make the request for a new one.

Since you are using pyfirecrest, you can get a valid access token at any moment with this
```python
client_id = "firecrest-sample"
client_secret = "b391e177-fa50-4987-beaf-e6d33ca93571"
token_uri = "http://localhost:8080/auth/realms/kcrealm/protocol/openid-connect/token"

keycloak = f7t.ClientCredentialsAuth(
    client_id, client_secret, token_uri
)
print(keycloak.get_access_token())
```

**Comment by simonbray** [comment]
Perfect! Thanks again!
