### ISSUE TITLE
Setting up a Demo

### ISSUE THREAD

**Issue by scavenqqer** [eth-cscs/firecrest#170]
Hello I want to test the demo file but i proceed after log in,
prompting "invalid parameter: redirecting_uri"

Help on this.  I'm doing this on a solo virtual machine, not on a HPC.

**Comment by jpdorsch** [comment]
Hi @scavenqqer, 

I'm assuming you are using the `docker-compose` file as explained in https://github.com/eth-cscs/firecrest/tree/master/deploy/demo, and that you are trying to run the `client` web application in your own VM.

If this is the case, the issue could be that the OIDC client `firecrest-sample` is not configured to point to your demo client URL.
By default, this value points to `http://localhost:7000` but this is only for local deployment.

In order to change that go to your browser to the demo Keycloak dashboard (which should be deployed in your VM in port 8080), use the default admin credentials (see in `README`), select `Clients`, and `firecrest-demo`, and look for the field `* Valid Redirect URIs` and set your demo client URL.

Remember that this redirection is done from your browser to the demo client URL, so, it can't be `localhost` since from what you explained you are deploying this in a VM. Therefore, I assume you should have an IP or a DNS for that host (ie, http://your-vm-dns:7000`)

Hope this helps, 
Cheers

**Comment by scavenqqer** [comment]
Thank you very much for this help. I was able to test it. 
I actually setup this on my VM and I want to test it with my slurm server, which connection should be changed? or in which part ? It's like my VM is the front-end and it will pass through my slurm server which is on the other server.
Hope for your repsonse on this. Thank you

**Comment by jpdorsch** [comment]
You have to configure SSH in the machine that you have SLURM.
If you look at demo cluster SSH configuration here https://github.com/eth-cscs/firecrest/blob/028edf3bf492c803f4033753f80f61e6747ce248/deploy/test-build/cluster/ssh/sshd_config#L100 it is configured to accept only SSH certificates that have been signed with that public key (`/etc/ssh/ca-key.pub`).
That public key is the same one that is configured in the `certificator` microservice (https://github.com/eth-cscs/firecrest/blob/028edf3bf492c803f4033753f80f61e6747ce248/deploy/demo/docker-compose.yml#L27).

Hope this helps,
Cheers.

**Comment by scavenqqer** [comment]
Thank you for the help.

Is docker-compose is the only way for the FirecREST to be setup ? or it should be on different machine ? 
Should it be on the front-end ? 
I'm very curios for the setup of this.

Hope to be answered. 
Thank you.

**Comment by scavenqqer** [comment]
Thanks much for the response and help.

I'm building it on one machine(FirecREST , KEYCLOAK, KONG) without using the Docker or Kurbenetes. 
Would it work ?

**Comment by jpdorsch** [comment]
Yes, as I mentioned in the comment above, that can be set without problems. 
Just be aware that Kong should be the only entry point for requests from outside the machine, and not interface FirecREST directly to external networks, only through the gateway.

Cheers

**Comment by jpdorsch** [comment]
Hi @scavenqqer, 

Can this issue be closed?

Thanks,

Cheers

**Comment by scavenqqer** [comment]
Hi @jpdorsch,

Yes, Thanks for the help and cooperation,
Thank you very much.
