### ISSUE TITLE
Feature request: tail starting with bytes/lines

### ISSUE THREAD

**Issue by henrique** [eth-cscs/firecrest#189]
Hi guys,

I'd like to use the reverse behaviour for _tail_, i.e. read from a seek position instead of reading the last bytes/lines.

https://man7.org/linux/man-pages/man1/tail.1.html
From the man-page, you can add an additional '+' to either -c or -n  to reverse the behaviour. 

Perhaps a starting_with_mode=True parameter?

This would be very useful when trying to follow the progress of a job's output, without having to call _stat_ beforehand.
Thanks heaps!
Cheers, 
Henrique

**Comment by henrique** [comment]
Hey guys,
Any update on this? :grimacing: 
This seems to be the only reliable way to follow logs as they happen. Unless you have another idea?
thanks!

**Comment by ekouts** [comment]
Hi Henrique! Sorry for not updating the issue, but this should be fixed in the latest release (https://github.com/eth-cscs/firecrest/releases/tag/v1.13.1) and it's already deployed.
The `tail` has a new boolean query parameter, `skip_beginning`. Could you please give it a try and let us know if this works fine for you?

**Comment by ekouts** [comment]
Hi @henrique, I will close this ticket, but let us know if you have any problem using the endpoint.
Cheers,
Eirini
