### ISSUE TITLE
`/utilities/stat` returns wrong header for non-existent file (in some cases)

### ISSUE THREAD

**Issue by chrisjsewell** [eth-cscs/firecrest#193]
~~The `stat` command will return e.g. `stat: unknown.txt: stat: No such file or directory` for a non-existent file.
However, this gets matched by: https://github.com/eth-cscs/firecrest/blob/0c43e3e27c6cbf0b6c09fe8b80baa73835c3ba8c/src/common/cscs_api_common.py#L708~~

Edit: so its actually only for some cases; when you have an existing file like `exists.txt` and then try to do `stat exists.txt/unknown.txt`.
Then it returns `stat: cannot stat 'exists.txt/unknown.txt': Not a directory`, and this is when it is not picked up by `No such file`...

meaning, it will return an `X-A-Directory` header instead of the correct `X-Invalid-Path` header.

In general also, it may be good to include the original error string for all these errors, i.e.

```python
return {"description": service_msg, "error": error_str, "status_code": 400, "header": header}
```

this would make it easier to debug

**Comment by jpdorsch** [comment]
Hi @chrisjsewell,

Thanks for pointing this out, we will fix it. Don't you think that would make more sense instead of using the proposed `X-Invalid-Path` to use `X-Not-A-Directory` for this error?

Given that the actual output of the error is `stat: cannot stat 'exists.txt/unknown.txt': Not a directory` for us it would be easier to implement and for clients it would be also more understandable in terms of the given error.

What do you think?

**Comment by jpdorsch** [comment]
Hi @chrisjsewell, 
we have included this fix in the newest [release](https://github.com/eth-cscs/firecrest/releases/tag/v1.13.1).
Please let us know if this fixes your issue.
Cheers
