### ISSUE TITLE
unable to detect symlink folder that owned by root

### ISSUE THREAD

**Issue by komraad** [eth-cscs/firecrest#198]
Hello,

It seems that Firecrest cannot detect the **symlink folder** that is owned by the root. It will display as text. 
Is there a possible way to detect it?
Thank you.

![image](https://github.com/eth-cscs/firecrest/assets/117581253/de242c6d-39c3-445d-bcfb-6ca47aba75b7)

**Comment by komraad** [comment]
Correction/addition to the issue.

Symlink is the issue, and the owner seems to be good already.

**Comment by jpdorsch** [comment]
HI @komraad,

Sorry for the delay on taking this issue. 

Just to fully understand your issue, what you say is that in the Web UI Client the symlink is shown as plain text instead of a hyperlink to the file/directory that is linked?

PS: we are not currently supporting the Web UI Client since we are going to provide a new one. This client was meant as an example of the usage of FirecREST.

Cheers,
Juan
